version: '3.9'

x-base_service: &base_service
    ports:
      - "${WEBUI_PORT:-7860}:7860"
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [compute, utility]

name: webui-docker

services:

  auto: &automatic
    <<: *base_service
    profiles: ["auto"]
    build: ./services/AUTOMATIC1111
    image: sd-auto:68
    environment:
      - CLI_ARGS=--allow-code --xformers --enable-insecure-extension-access --api
    volumes:
      - output:/output
      - models-sd:/data/models/Stable-diffusion
      - models-lora:/data/models/Lora
      - models-controlnet:/data/models/ControlNet
      - models-vae:/data/models/VAE

  auto-cpu:
    <<: *automatic
    profiles: ["auto-cpu"]
    deploy: {}
    environment:
      - CLI_ARGS=--no-half --precision full --allow-code --enable-insecure-extension-access --api

  invoke: &invoke
    <<: *base_service
    profiles: ["invoke"]
    build: ./services/invoke/
    image: sd-invoke:30
    environment:
      - PRELOAD=true
      - CLI_ARGS=--xformers

  # invoke-cpu:
  #   <<: *invoke
  #   profiles: ["invoke-cpu"]
  #   environment:
  #     - PRELOAD=true
  #     - CLI_ARGS=--always_use_cpu

  comfy: &comfy
    <<: *base_service
    profiles: ["comfy"]
    build: ./services/comfy/
    image: sd-comfy:5
    environment:
      - CLI_ARGS=


  comfy-cpu:
    <<: *comfy
    profiles: ["comfy-cpu"]
    deploy: {}
    environment:
      - CLI_ARGS=--cpu

volumes:
  output:
    name: "output"
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/output
      o: bind
  models-sd:
    name: "models-sd"
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/models-sd
      o: bind,ro
  models-lora:
    name: "models-lora"
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/models-lora
      o: bind,ro
  models-controlnet:
    name: "models-controlnet"
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/models-controlnet
      o: bind,ro
  models-vae:
    name: "models-vae"
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/models-vae
      o: bind,ro
